# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - obabappweb

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://marioobabaldbiyat.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d7fe3f080020405abc914681f28a6f5c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_05820a38e8a344c7858ff08b9802105f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: marioobabaldbiyat.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d7fe3f080020405abc914681f28a6f5c }}/mario-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'obabappweb'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7cc13677fbbf4844ae7fb659e896962c }}
        images: 'marioobabaldbiyat.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d7fe3f080020405abc914681f28a6f5c }}/mario-api:${{ github.sha }}'